data_name: 'RAVDESS'
sub_name: 'cnn_to_transformer'

dataset: 'dataset/Actor_*/*.wav'
npy_name: 'features+labels.npy'

sample_rate: 48000
minibatch: 256  # pick minibatch size (of 32... always)
num_epochs: 500

device: 'cuda'